### ISSUE TITLE
joining public testnet

### ISSUE THREAD

**Issue by Daniel1984** [kardiachain/go-kardia#177]
Following steps from [here](https://github.com/kardiachain/go-kardia/tree/master/deployment/testnet)

When running docker-compose getting this:

```
testnet-node    | panic: abi: cannot use array as type ptr as argument
testnet-node    | 
testnet-node    | goroutine 1 [running]:
testnet-node    | github.com/kardiachain/go-kardia/mainchain/staking.(*StakingSmcUtil).CreateGenesisValidator(0xc00020d580, 0xc000188690, 0xc000001c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/mainchain/staking/staking_smc.go:136 +0x69a
testnet-node    | github.com/kardiachain/go-kardia/mainchain/genesis.setupGenesisStaking(0xc00020d580, 0xc000188690, 0xc000001c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/mainchain/genesis/genesis.go:352 +0x4a1
testnet-node    | github.com/kardiachain/go-kardia/mainchain/genesis.(*Genesis).ToBlock(0xc000139200, 0x1343200, 0xc000af6de0, 0x1340fc0, 0xc00020cec0, 0xc00020d580, 0x1ade3ff, 0x0, 0x0, 0x0, ...)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/mainchain/genesis/genesis.go:214 +0x61f
testnet-node    | github.com/kardiachain/go-kardia/mainchain/genesis.(*Genesis).Commit(0xc000139200, 0x1343200, 0xc000af6de0, 0x13553e0, 0xc000206940, 0xc00020d580, 0x17, 0x0, 0x0)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/mainchain/genesis/genesis.go:227 +0x95
testnet-node    | github.com/kardiachain/go-kardia/mainchain/genesis.SetupGenesisBlock(0x1343200, 0xc000af6de0, 0x13553e0, 0xc000206940, 0xc000139200, 0xc00020d580, 0x40fd56, 0x0, 0x0, 0x0, ...)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/mainchain/genesis/genesis.go:124 +0x1a4
testnet-node    | github.com/kardiachain/go-kardia/mainchain.newKardiaService(0xc00020d340, 0xc0002b4460, 0x7f40f6c49108, 0xc000aefb70, 0x40fd56)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/mainchain/kardia_service.go:112 +0x227
testnet-node    | github.com/kardiachain/go-kardia/mainchain.NewKardiaService(0xc00020d340, 0xc000af6d80, 0xc000aefd78, 0xc0005839f0, 0x10)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/mainchain/kardia_service.go:197 +0x19c
testnet-node    | github.com/kardiachain/go-kardia/node.(*Node).OnStart(0xc0000e8420, 0x0, 0x0)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/node/node.go:239 +0x2e6
testnet-node    | github.com/kardiachain/go-kardia/lib/service.(*BaseService).Start(0xc0000e8420, 0x11cf288, 0x0)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/lib/service/service.go:145 +0x2f5
testnet-node    | main.(*Config).Start(0xc000127b00)
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/cmd/main.go:406 +0x484
testnet-node    | main.main()
testnet-node    | 	/go/src/github.com/kardiachain/go-kardia/cmd/main.go:600 +0xc9
testnet-node exited with code 2
```

**Comment by Sonek-HoangBui** [comment]
Actually, the example is not working, because the source code and smart contract are in different versions. So you need to link manually.
The problem here is "Seed nodes", I can't find any seed nodes... :slightly_smiling_face: So please update or provide some information about it. Thanks so much
